---
# tasks file for ./roles/apache
- name: Install httpd Package
  yum: name=httpd state=latest

- name: Copy httpd configuration file
  copy: src=files/httpd.original dest=/etc/httpd/conf/httpd.conf

- name: Copy index.html file
  copy: src=files/index.html dest=/var/www/html
  notify:
  - restart apache

- name: Start and Enable httpd service
  service: name=httpd state=restarted enabled=yes